vim.keymap.set("n", "<C-n>", "<Cmd>BufferNext<CR>")
vim.keymap.set("n", "<C-p>", "<Cmd>BufferPrevious<CR>")
vim.keymap.set("n", "<C-q>", "<Cmd>BufferClose<CR>")
vim.keymap.set("n", "<leader>fo", "<Cmd>Neotree action=focus reveal toggle<CR>", { silent = true })
vim.keymap.set("n", "<C-h>", "<C-w><")
vim.keymap.set("n", "<C-j>", "<C-w>-")
vim.keymap.set("n", "<C-k>", "<C-w>+")
vim.keymap.set("n", "<C-l>", "<C-w>>")
vim.keymap.set({"n", "v"}, "<leader>", "<Nop>")
vim.keymap.set("n", "ZZ", "<Nop>")
vim.keymap.set("n", "ZQ", "<Nop>")
vim.keymap.set("n", "q", "<Nop>")
vim.keymap.set("n", "Q", "<Nop>")
vim.keymap.set("n", "<S-l>", "<C-w>l")
vim.keymap.set("n", "<S-h>", "<C-w>h")
vim.keymap.set("n", "<S-k>", "<C-w>k")
vim.keymap.set("n", "<S-j>", "<C-w>j")
vim.keymap.set("n", "[LSP]", "<Nop>")
vim.keymap.set("n", "[LSP]", "<leader>l", { remap = true })
vim.keymap.set("n", "[GIT]", "<Nop>")
vim.keymap.set("n", "[GIT]", "<leader>g", { remap = true })
